### PR TITLE
Generate new Anchore client

### PR DESCRIPTION
**Pull request by pbalogh-sa**
- Makefile which contains client generation
- Generate new Anchore client
- Some fixes due to the new Anchore client

cc @zhill

### CODE REVIEW

**Comment by pbalogh-sa** [comment]
I have to fix tests as well.

**Comment by zhill** [comment]
This is definitely needed, but I'd like to split this out into its own repo so we can re-use it in other projects as well. What do you think about that? I can create a new anchore repo and we can start work there on a maintained client and consume that in this project.

**Comment by pbalogh-sa** [comment]
I agree with you. In this way, we have to concentrate on maintaining only the admission-controller in this repo.

**Comment by zhill** [comment]
I created a new repo: https://github.com/anchore/client-go to hold the new code. But, I think merging this first so it works, and then making the switch is the best approach.

**Comment by pbalogh-sa** [comment]
@zhill , The generated client seems to break in case of adding an image to analysis.
```
I1016 09:04:10.696348       1 main.go:341] Image is not analyzed
I1016 09:04:10.696485       1 main.go:294] Requesting analysis of image image=poke/kafka-operator
I1016 09:04:10.696534       1 main.go:322] Performing passive validation. Will request image analysis and always allow admission
E1016 09:04:10.849970       1 main.go:327] Error from analysis request err=400 Bad Request
I1016 09:04:10.850062       1 main.go:317] Returning status=&AdmissionResponse{UID:b04ea963-14f4-433b-955f-89253b2d5871,Allowed:false,Result:&k8s_io_apimachinery_pkg_apis_meta_v1.Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,},Status:Failure,Message:Image poke/kafka-operator is not analyzed.,Reason:,Details:nil,Code:0,},Patch:nil,PatchType:nil,AuditAnnotations:map[string]string{},}
```

**Comment by pbalogh-sa** [comment]
the catalog log:
```
[service:catalog] 2019-10-16 09:12:44+0000 [-] Traceback (most recent call last):
[service:catalog] 2019-10-16 09:12:44+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 282, in image
[service:catalog] 2019-10-16 09:12:44+0000 [-]     raise err
[service:catalog] 2019-10-16 09:12:44+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 280, in image
[service:catalog] 2019-10-16 09:12:44+0000 [-]     raise Exception("image data not found in DB")
[service:catalog] 2019-10-16 09:12:44+0000 [-] Exception: image data not found in DB
[service:catalog] 2019-10-16 09:12:44+0000 [_GenericHTTPChannelProtocol,88747,10.12.2.213] [PoolThread-twisted.internet.reactor-2] [anchore_engine.services.catalog.catalog_impl/image()] [ERROR] Error processing image request
[service:catalog] 2019-10-16 09:12:44+0000 [-] "10.12.2.213" - - [16/Oct/2019:09:12:44 +0000] "GET /v1/images?tag=poke%2Fkafka-operator&registry_lookup=False HTTP/1.1" 404 106 "-" "python-requests/2.20.0"
[service:catalog] 2019-10-16 09:12:51+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:12:50 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:12:53+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:12:52 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:01+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:00 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:03+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:02 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:11+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:10 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:13+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:12 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:21+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:20 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:23+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:22 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:31+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:30 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:33+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:32 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:35+0000 [-] Traceback (most recent call last):
[service:catalog] 2019-10-16 09:13:35+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 282, in image
[service:catalog] 2019-10-16 09:13:35+0000 [-]     raise err
[service:catalog] 2019-10-16 09:13:35+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 280, in image
[service:catalog] 2019-10-16 09:13:35+0000 [-]     raise Exception("image data not found in DB")
[service:catalog] 2019-10-16 09:13:35+0000 [-] Exception: image data not found in DB
[service:catalog] 2019-10-16 09:13:35+0000 [_GenericHTTPChannelProtocol,88758,10.12.2.213] [PoolThread-twisted.internet.reactor-3] [anchore_engine.services.catalog.catalog_impl/image()] [ERROR] Error processing image request
[service:catalog] 2019-10-16 09:13:35+0000 [-] "10.12.2.213" - - [16/Oct/2019:09:13:34 +0000] "GET /v1/images?tag=poke%2Fkafka-operator&registry_lookup=False HTTP/1.1" 404 106 "-" "python-requests/2.20.0"
[service:catalog] 2019-10-16 09:13:36+0000 [-] Traceback (most recent call last):
[service:catalog] 2019-10-16 09:13:36+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 282, in image
[service:catalog] 2019-10-16 09:13:36+0000 [-]     raise err
[service:catalog] 2019-10-16 09:13:36+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 280, in image
[service:catalog] 2019-10-16 09:13:36+0000 [-]     raise Exception("image data not found in DB")
[service:catalog] 2019-10-16 09:13:36+0000 [-] Exception: image data not found in DB
[service:catalog] 2019-10-16 09:13:36+0000 [_GenericHTTPChannelProtocol,88759,10.12.2.213] [PoolThread-twisted.internet.reactor-4] [anchore_engine.services.catalog.catalog_impl/image()] [ERROR] Error processing image request
[service:catalog] 2019-10-16 09:13:36+0000 [-] "10.12.2.213" - - [16/Oct/2019:09:13:36 +0000] "GET /v1/images?tag=poke%2Fkafka-operator&registry_lookup=False HTTP/1.1" 404 106 "-" "python-requests/2.20.0"
```

**Comment by pbalogh-sa** [comment]
Maybe I have some problems with my anchore-engine.

**Comment by pbalogh-sa** [comment]
The generated client will be correct If the [OpenapiTools issue](https://github.com/OpenAPITools/openapi-generator/issues/3159) is fixed.

**Comment by zhill** [comment]
@pbalogh-sa are you waiting on the upstream fix, or did you do a workaround and this is ready to review/test/merge? No rush, just making sure I'm not blocking your progress

**Comment by pbalogh-sa** [comment]
@zhill I have been waiting for the upstream fix, but it hasn't arrived yet. So I will work around it the next week and submit a PR.

**Comment by pbalogh-sa** [comment]
@zhill I've fixed the bug in the generated client (using sed in the Makefile).

**Pull request merged**
